runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /static
  static_dir: static
 
- url: /_ah/api/.*
  script: tempreport.api_endpoint
 
- url: /
  static_files: static/graphs.html
  upload: static
   
 
libraries:
- name: pycrypto
  version: latest
- name: ssl
  version: 2.7.11